### ISSUE TITLE
Processing Fractal details.

### ISSUE THREAD

**Issue by regrocsi** [near-ndc/i-am-human-dapp#230]
It's been 7 days since I haven't been able to register my NEAR address on I-Am-Human. Everything goes smoothly until step 02, the Face Scan does everything correctly, and my identity is already there on Fractal id. It requests authorization for I-Am-Human to consult, says my identity is already approved, and directs me to the I-Am-Human website, but it stays indefinitely on the message 'Processing Fractal details. I am using the Here wallet or MyNearWallet.
![i-am-human](https://github.com/near-ndc/i-am-human-dapp/assets/92496088/0904cc24-440d-457a-9fa3-3fc19f2cc59f)
![fractual](https://github.com/near-ndc/i-am-human-dapp/assets/92496088/31c7aee2-d8fe-489e-a35d-0307ef4fa894)

**Comment by Genesisman001** [comment]
I've been experiencing the same thing now for over a month 
![Screenshot_20240213-063101_Brave](https://github.com/near-ndc/i-am-human-dapp/assets/159666675/1f842d7c-9fa9-4264-bdd1-aa17b674cb48)

**Comment by Megha-Dev-19** [comment]
Hey sorry for the issue, we are working on it

**Comment by Megha-Dev-19** [comment]
This issue has been resolved, please try again and let me know if you still face an issue.

**Comment by regrocsi** [comment]
Perfect, now everything is working, Tanks
