### ISSUE TITLE
Problem with https://i-am-human.app/

### ISSUE THREAD

**Issue by fgex8** [near-ndc/i-am-human-dapp#53]
Can you have a look at my validation ? I followed all steps , have a https://wallet.gooddollar.org/ account with facial id (0xa1ade0b4c6b7d9dc9a7e1f8770eca5edde233ab3) . I connected it with my nearwallet (fgex.near) but now it doesnt mint the nft and doesnt validate my humanity 

Can you have a look ? Thank you

**Comment by janewang** [comment]
I-AM-HUMAN is no longer using good dollar. Please test again.
